CREATE DATABASE DUAN1_NHOM6
USE DUAN1_NHOM6
GO

CREATE TABLE ChucVu(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(50) DEFAULT NULL,
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0
)
Create TABLE NHANVIEN(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MANV VARCHAR(20) UNIQUE,
HoTen NVARCHAR(50) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
GioiTinh NVARCHAR(25) DEFAULT NULL,
DiaChi NVARCHAR(200) DEFAULT NULL,
Sdt VARCHAR(10) DEFAULT NULL,
Email VARCHAR(100) DEFAULT NULL,
MatKhau VARCHAR(20),
IDCV UNIQUEIDENTIFIER,
Hinh VARCHAR(50),
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0
)
CREATE TABLE MauSac(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0
)
CREATE TABLE ChatLieu(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0
)
CREATE TABLE DoCao(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0
)
CREATE TABLE DanhMuc(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0
)
CREATE TABLE Size(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0
)
CREATE TABLE GiaoCa(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaGC VARCHAR(20) UNIQUE,
MaNVGiao VARCHAR(20) UNIQUE,
MaNVNhan VARCHAR(20) UNIQUE,
GioNhanCa FLOAT DEFAULT NULL,
GioGiaoCa FLOAT DEFAULT NULL,
TienCoso FLOAT DEFAULT NULL,
TienPhatSinh FLOAT DEFAULT NULL,
DoanhThuCa FLOAT DEFAULT NULL,
TongTien FLOAT DEFAULT NULL,
GhiChuGiao NVARCHAR(200) DEFAULT NULL,
GhiChuNhan NVARCHAR(200) DEFAULT NULL,
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0
)

CREATE TABLE KhachHang(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaKH VARCHAR(20) UNIQUE,
LoaiKH NVARCHAR(50) DEFAULT NULL,
TenKH NVARCHAR(50) DEFAULT NULL,
DiaChi NVARCHAR(200) DEFAULT NULL,
GioiTinh NVARCHAR(50) DEFAULT NULL,
Email VARCHAR(50) DEFAULT NULL,
SDT VARCHAR(50) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
NgayThamGia DATE DEFAULT NULL,

)
CREATE TABLE ChiTietSanPham(
IdCTSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaSP VARCHAR(20) UNIQUE,
MaKM VARCHAR(20) UNIQUE,
TenSP NVARCHAR(50),
GiaBan DECIMAL(20,0) DEFAULT 0,
GiaTien DECIMAL(20,0) DEFAULT 0,
QR VARCHAR(50),
HinhAnh VARCHAR(50),
SoLuong int,
DanhMuc NVARCHAR(50),
size int,
MauSac NVARCHAR(50),
ChatLieu NVARCHAR(50),
DoCao int,
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0
)
CREATE TABLE SanPham(
IdSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaSP VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
SoLuong int ,
QR  VARCHAR(50),
DonGia DECIMAL(20,0) DEFAULT 0,
MoTa NVARCHAR(100),
HinhAnh VARCHAR(50),
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0
)
CREATE TABLE GiaoHang(
IDGH UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaHD VARCHAR(20) UNIQUE,
TenKH NVARCHAR(50),
SDT VARCHAR(50),
DiaChi NVARCHAR(50) DEFAULT NULL,
GiamGia VARCHAR(50) DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
NgayNhan DATE DEFAULT NULL,
NgayTao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0
)
CREATE TABLE HoaDon(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaHD VARCHAR(20) UNIQUE,
MANV VARCHAR(20) UNIQUE,
MaKH VARCHAR(20) UNIQUE,
NgayMua DATE DEFAULT NULL,
GiamGia VARCHAR(30) DEFAULT NULL,
ThanhTien DECIMAL(20,0) DEFAULT 0,
maKM	VARCHAR(20) UNIQUE NULL,
GhiChu NVARCHAR(100) DEFAULT NULL,
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0
)

CREATE TABLE ChiTietHoaDon(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaHD VARCHAR(20) UNIQUE,
MaSP VARCHAR(20) UNIQUE,
TenSP NVARCHAR(50) DEFAULT NULL,
QR  VARCHAR(50) DEFAULT NULL,
GiaTien FLOAT DEFAULT NULL,
SoLuong INT DEFAULT NULL,
Dmuc  NVARCHAR(200) DEFAULT NULL,
Size  INT DEFAULT NULL,
MauSac NVARCHAR(200) DEFAULT NULL,
ChatLieu  NVARCHAR(200) DEFAULT NULL,
DoCao INT DEFAULT NULL,
NgayBan Date  DEFAULT NULL,
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0

)
CREATE TABLE KhuyenMai(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
maKM	VARCHAR(20) UNIQUE NULL,
tenKM NVARCHAR(20) NULL,
giaTri INT NULL,
giamToiDa INT null,
ngayBatDau DATE DEFAULT NULL,
ngayKetThuc DATE DEFAULT NULL,
hinhThucApDung NVARCHAR(50),
apDungGiamGia NVARCHAR(50),
loaiGiamGia NVARCHAR(50) NULL,
maGiamGia VARCHAR(20) NULL,
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0

)

CREATE TABLE GioHang(
IdGH UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdKH UNIQUEIDENTIFIER,
IdNV UNIQUEIDENTIFIER,
Ma VARCHAR(20) UNIQUE,
NgayThanhToan DATE DEFAULT NULL,
TenNguoiNhan NVARCHAR(50) DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
Sdt VARCHAR(30) DEFAULT NULL,
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0

)


CREATE TABLE GioHangChiTiet(
IdGH UNIQUEIDENTIFIER,
IdCTSP UNIQUEIDENTIFIER,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0,
DonGiaKhiGiam DECIMAL(20,0) DEFAULT 0,
NgayTao DATE DEFAULT NULL,
NgayGiao DATE DEFAULT NULL,
TrangThai INT DEFAULT 0
PRIMARY KEY (IdGH,IdCTSP)
)

ALTER TABLE NHANVIEN ADD FOREIGN KEY (IDCV) REFERENCES CHUCVU(ID)
ALTER  TABLE GiaoCa ADD FOREIGN KEY (MaNVGiao) REFERENCES NHANVIEN(MANV)
ALTER TABLE HOADON ADD FOREIGN KEY (MANV) REFERENCES NHANVIEN(MaNV)
ALTER TABLE HOADON ADD FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MaKM)
ALTER TABLE CHITIETHOADON ADD FOREIGN KEY (ID) REFERENCES HOADON(ID)
ALTER TABLE KHACHHANG ADD FOREIGN KEY (MAKH) REFERENCES HOADON(MaKH)
ALTER TABLE GIAOHANG ADD FOREIGN KEY (MAHD) REFERENCES HOADON(MaHD)
ALTER TABLE CHITIETHOADON ADD FOREIGN KEY (ID) REFERENCES ChiTietSanPham(IdCTSP)
ALTER TABLE CHITIETSANPHAM ADD FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
ALTER TABLE CHITIETSANPHAM ADD FOREIGN KEY (IdCTSP) REFERENCES DANHMUC(ID)
ALTER TABLE CHITIETSANPHAM ADD FOREIGN KEY (IdCTSP) REFERENCES SIZE(ID)
ALTER TABLE CHITIETSANPHAM ADD FOREIGN KEY (IdCTSP) REFERENCES MAUSAC(ID)
ALTER TABLE CHITIETSANPHAM ADD FOREIGN KEY (IdCTSP) REFERENCES CHATLIEU(ID)
ALTER TABLE CHITIETSANPHAM ADD FOREIGN KEY (IdCTSP) REFERENCES DOCAO(ID)
ALTER TABLE CHITIETSANPHAM ADD FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM)
ALTER TABLE GIOHANGCHITIET ADD FOREIGN KEY (IdCTSP) REFERENCES CHITIETSANPHAM(IdCTSP)
ALTER TABLE GIOHANGCHITIET ADD FOREIGN KEY (IdGH) REFERENCES GIOHANG(IdGH)


