SELECT * FROM HoaDon
UPDATE HoaDon SET TRANGTHAI =2 WHERE ID='14E1863B-9ECA-4CF0-BB7F-4FA5DE804B1F'
UPDATE HOADON SET THANHTIEN=(SELECT SUM(DONGIA*SOLUONG) FROM ChiTietHoaDon WHERE IDHD='6108264C-5E64-4395-B945-F91B42E90593')  WHERE ID='6108264C-5E64-4395-B945-F91B42E90593'
SELECT * FROM HOADON WHERE DAY(NgayTao)=DAY(GETDATE()) AND TrangThai=2
ALTER FUNCTION FNDTNGAY(@ngay DATE)
RETURNS @dtngay TABLE (doanhthu Decimal,thanhcong int,bihuy int)
AS
begin
DECLARE @dt decimal=0,@tc int=0,@bihuy int=0;
 SELECT @dt=SUM(THANHTIEN) FROM HOADON WHERE DAY(NgayMua)=DAY(@ngay) AND TRANGTHAI=1
 SELECT @tc= COUNT(MAHD) FROM HOADON WHERE DAY(NgayMua)=DAY(@ngay) AND TRANGTHAI=1
 SELECT @bihuy=  COUNT( MAHD ) FROM HOADON WHERE DAY(NGAYTAO)=DAY(@ngay) AND TRANGTHAI=2
INSERT INTO @dtngay VALUES(@dt,@tc,@bihuy)
RETURN
end

SELECT COUNT(MAHD) FROM HOADON WHERE TRANGTHAI=1 
SELECT * FROM dbo.FNDTTHANG(GETDATE())
SELECT SUM(ThanhTien)AS DT,(SELECT COUNT(MAHD)FROM HOADON WHERE TRANGTHAI=1) AS SODON FROM HoaDon 
GROUP BY THANHTIEN,MAHD
SELECT COUNT(MAHD) FROM HOADON
SELECT * FROM HOADON
UPDATE HOADON SET NgayTao='2022-02-03' WHERE MaHD='HD3'
CREATE PROC SP_DTCACNAM 
as
begin
	SELECT YEAR(ngaytao)as [year], COUNT(MAHD) AS SODON,SUM(ThanhTien) AS DoanhThu FROM HOADON where trangthai=1  group by year(ngaytao)
end
EXEC SP_DTCACNAM
SELECT DISTINCT Month(NGAYTAO) as [YEAR] FROM HOADON WHERE NGAYTAO IS NOT NULL ORDER BY [YEAR] DESC
select * from ChiTietSanPham
SELECT * FROM KhachHang
delete FROM ChiTietHoaDon where idctsp='D6718367-AE49-402F-9FC4-A2AE23D498B2'
SELECT * from khuyenmai
delete from ChiTietSanPham where id='D6718367-AE49-402F-9FC4-A2AE23D498B2'
select * from chitietsanpham
select * from ChiTietHoaDon
SELECT * FROM dbo.FNDTNGAY(getdate())
SELECT * FROM HOADON
ALTER TRIGGER SoLuong ON CHITIETSANPHAM AFTER UPDATE AS
BEGIN
	IF (SELECT INSERTED.SOLUONG FROM CHITIETSANPHAM JOIN INSERTED ON CHITIETSANPHAM.ID=INSERTED.ID)>0
	BEGIN
	UPDATE CHITIETSANPHAM SET TRANGTHAI=1 FROM CHITIETSANPHAM JOIN INSERTED ON CHITIETSANPHAM.ID=INSERTED.ID
	END
END
select * from GIAOHANG
CREATE TRIGGER HUYKHUYENMAI ON KHUYENMAI AFTER UPDATE AS
BEGIN
	IF(SELECT INSERTED.TRANGTHAI FROM KHUYENMAI JOIN INSERTED ON KHUYENMAI.ID=INSERTED.ID)=1
	BEGIN
	UPDATE CHITIETSANPHAM SET IDKM=NULL FROM CHITIETSANPHAM JOIN INSERTED ON CHITIETSANPHAM.IDKM=INSERTED.ID
	END
END
SELECT MAKH,TENKH,SDT,NGAYMUA,SUM(THANHTIEN) FROM KHACHHANG JOIN HOADON ON KHACHHANG.ID=HOADON.IDKH GROUP BY MAKH,TENKH,SDT,NGAYMUA,THANHTIEN
UPDATE HOADON SET TRANGTHAI=0 WHERE MaHD='HD5'
UPDATE KHACHHANG SET NGAYTHAMGIA='2023-04-02' WHERE MAKH='KH01'
SELECT Month(ngaytao)as [month], COUNT(MAHD) AS SODON,SUM(ThanhTien) AS DoanhThu FROM HOADON where trangthai=1 and year(ngaytao)=2023 group by month(ngaytao)
SELECT * FROM GiaoHang

SELECT dbo.ChatLieu.Ten, dbo.ChiTietHoaDon.SoLuong, dbo.ChiTietHoaDon.DonGia, dbo.ChiTietHoaDon.NgayBan, dbo.DanhMuc.Ten AS DanhMuc, dbo.DoCao.Ten AS DoCao, dbo.HoaDon.MaHD, dbo.KhachHang.TenKH, dbo.KhachHang.DiaChi, 
                  dbo.KhachHang.SDT, dbo.MauSac.Ten AS MauSac, dbo.NhanVien.HoTen, dbo.SanPham.Ten AS SanPham, dbo.Size.Ten AS Size, dbo.ChiTietSanPham.GiaBan, dbo.HoaDon.ThanhTien, (dbo.ChiTietHoaDon.SoLuong*dbo.ChiTietHoaDon.DonGia) AS Gia
FROM     dbo.ChiTietSanPham INNER JOIN
                  dbo.ChiTietHoaDon ON dbo.ChiTietSanPham.Id = dbo.ChiTietHoaDon.IDCTSP INNER JOIN
                  dbo.ChatLieu ON dbo.ChatLieu.Id = dbo.ChiTietSanPham.ChatLieu AND dbo.ChiTietHoaDon.IDCTSP = dbo.ChiTietSanPham.Id INNER JOIN
                  dbo.DanhMuc ON dbo.ChiTietSanPham.DanhMuc = dbo.DanhMuc.Id INNER JOIN
                  dbo.DoCao ON dbo.ChiTietSanPham.DoCao = dbo.DoCao.Id INNER JOIN
                  dbo.HoaDon ON dbo.ChiTietHoaDon.IDHD = dbo.HoaDon.ID INNER JOIN
                  dbo.KhachHang ON dbo.HoaDon.IDKH = dbo.KhachHang.ID INNER JOIN
                  dbo.MauSac ON dbo.ChiTietSanPham.MauSac = dbo.MauSac.Id INNER JOIN
                  dbo.NhanVien ON dbo.HoaDon.IDNV = dbo.NhanVien.Id INNER JOIN
                  dbo.SanPham ON dbo.ChiTietSanPham.IDSP = dbo.SanPham.Id INNER JOIN
                  dbo.Size ON dbo.ChiTietSanPham.Size = dbo.Size.Id

 WHERE MAHD='HD5'
alter table giaohang add ghichu nvarchar(200)

select * from HoaDon
select* from ChiTietHoaDon

INSERT INTO GIAOHANG(IDGH,IDHD,IDKH,SDT,DIACHI,TIENHANG,TIENSHIP,TONGTIEN,NGAYGIAO,NGAYNHAN,NGAYTAO,TRANGTHAI) VALUES (NEWID(),?,?,?,?,?,?,?,?,?,?,?)