SELECT * FROM HoaDon
UPDATE HoaDon SET TRANGTHAI =2 WHERE ID='14E1863B-9ECA-4CF0-BB7F-4FA5DE804B1F'
UPDATE HOADON SET THANHTIEN=(SELECT SUM(DONGIA*SOLUONG) FROM ChiTietHoaDon WHERE IDHD='6108264C-5E64-4395-B945-F91B42E90593')  WHERE ID='6108264C-5E64-4395-B945-F91B42E90593'
SELECT * FROM HOADON WHERE DAY(NgayTao)=DAY(GETDATE()) AND TrangThai=2
CREATE FUNCTION FNDTNAM(@ngay DATE)
RETURNS @dtngay TABLE (doanhthu Decimal,thanhcong int,bihuy int)
AS
begin
DECLARE @dt decimal=0,@tc int=0,@bihuy int=0;
 SELECT @dt=SUM(THANHTIEN) FROM HOADON WHERE year(NGAYTAO)=year(@ngay)
 SELECT @tc=(SELECT COUNT(MAHD) FROM HOADON WHERE TRANGTHAI=1) FROM HOADON WHERE year(NGAYTAO)=year(@ngay)
 SELECT @bihuy= (SELECT COUNT( MAHD )FROM HOADON WHERE TRANGTHAI=2) FROM HOADON WHERE year(NGAYTAO)=year(@ngay)
INSERT INTO @dtngay VALUES(@dt,@tc,@bihuy)
RETURN
end
SELECT * FROM dbo.FNDTNAM(GETDATE())
SELECT SUM(ThanhTien)AS DT,(SELECT COUNT(MAHD)FROM HOADON WHERE TRANGTHAI=1) AS SODON FROM HoaDon 
GROUP BY THANHTIEN,MAHD
SELECT COUNT(MAHD) FROM HOADON


