/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.newgui;

import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import poly.dao.GiaoCaDAO;
import poly.dao.NhanVienDao;
import poly.entity.GiaoCa;
import poly.entity.NhanVien;
import poly.helper.Auth;
import poly.helper.XDate;
import java.util.Locale;
import org.apache.log4j.helpers.DateTimeDateFormat;
import poly.helper.Messeger;

/**
 *
 * @author NTV
 */
public class GiaoCaFrm extends javax.swing.JDialog {

    private NhanVienDao nvDAO;
    private GiaoCaDAO gcDAO;
    private CardLayout gcCard;
    private List<NhanVien> lst;
    private Locale localeVN = new Locale("vi", "VN");
    private NumberFormat df = NumberFormat.getCurrencyInstance(localeVN);
    private DateTimeDateFormat dtdf = new DateTimeDateFormat();
    private int maGC;

    /**
     * Creates new form GiaoCaJDialog
     */
    public GiaoCaFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        faCard = new javax.swing.JPanel();
        cardGC = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblNVGiao = new javax.swing.JLabel();
        lblStartTime = new javax.swing.JLabel();
        lblEndTime = new javax.swing.JLabel();
        lblTienCS = new javax.swing.JLabel();
        lblDTCa = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        radThu = new javax.swing.JRadioButton();
        radChi = new javax.swing.JRadioButton();
        txtTienPhatSinh = new javax.swing.JTextField();
        lblTongTien = new javax.swing.JLabel();
        cbxNV = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        cardNC = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblNCcardNVNC = new javax.swing.JLabel();
        lblcardNCNVGC = new javax.swing.JLabel();
        lblcardNCStartTime = new javax.swing.JLabel();
        lblCardNCTienCoSo = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        lblCardNCTienPhatSinh = new javax.swing.JLabel();
        lblCardNCDoanhThuCa = new javax.swing.JLabel();
        lblCardNCTongTien = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        btnCardNCOK = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        sp = new javax.swing.JScrollPane();
        txtCardNCGhiChu = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        faCard.setLayout(new java.awt.CardLayout());

        cardGC.setBackground(new java.awt.Color(0, 255, 255));
        cardGC.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(890, 40));

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NHÂN VIÊN GIAO CA");
        jLabel1.setPreferredSize(new java.awt.Dimension(167, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1206, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 58, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 58, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );

        cardGC.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 255, 255)));
        jPanel1.setLayout(new java.awt.BorderLayout(50, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 25, new java.awt.Color(255, 255, 255)));
        jPanel3.setPreferredSize(new java.awt.Dimension(290, 577));
        jPanel3.setLayout(new java.awt.GridLayout(9, 0, 0, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nhân viên:");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Thời gian bắt đầu:");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Thời gian kết thúc:");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Tiền duy trì hoạt động:");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel6);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Doanh thu ca:");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel9);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Tiền phát sinh:");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel7);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Tổng tiền:");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Nhân viên nhận:");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel11);

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 100, 0, 15, new java.awt.Color(255, 255, 255)));
        jPanel4.setMaximumSize(new java.awt.Dimension(600, 439));
        jPanel4.setPreferredSize(new java.awt.Dimension(600, 439));
        jPanel4.setLayout(new java.awt.GridLayout(9, 0, 0, 10));

        lblNVGiao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(lblNVGiao);

        lblStartTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(lblStartTime);

        lblEndTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(lblEndTime);

        lblTienCS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(lblTienCS);

        lblDTCa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(lblDTCa);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(255, 40));
        jPanel9.setLayout(new java.awt.GridLayout(1, 2, 0, 10));

        buttonGroup1.add(radThu);
        radThu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radThu.setSelected(true);
        radThu.setText("Thu");
        radThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radThuActionPerformed(evt);
            }
        });
        jPanel9.add(radThu);

        buttonGroup1.add(radChi);
        radChi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        radChi.setText("Chi");
        radChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radChiActionPerformed(evt);
            }
        });
        jPanel9.add(radChi);

        jPanel8.add(jPanel9, java.awt.BorderLayout.WEST);

        txtTienPhatSinh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTienPhatSinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTienPhatSinhFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTienPhatSinhFocusLost(evt);
            }
        });
        txtTienPhatSinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienPhatSinhKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienPhatSinhKeyReleased(evt);
            }
        });
        jPanel8.add(txtTienPhatSinh, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel8);

        lblTongTien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(lblTongTien);

        cbxNV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(cbxNV);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 0, 15, new java.awt.Color(255, 255, 255)));
        jPanel5.setPreferredSize(new java.awt.Dimension(1090, 240));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Ghi chú:");
        jLabel3.setPreferredSize(new java.awt.Dimension(426, 20));
        jPanel5.add(jLabel3, java.awt.BorderLayout.WEST);

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 10, 0, new java.awt.Color(255, 255, 255)));
        jPanel6.setPreferredSize(new java.awt.Dimension(1060, 60));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel7.setLayout(new java.awt.GridLayout(1, 2, 15, 0));

        btnOk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOk.setText("Xác nhận");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jPanel7.add(btnOk);

        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHuy.setText("Huỷ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel7.add(btnHuy);

        jPanel6.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        cardGC.add(jPanel1, java.awt.BorderLayout.CENTER);

        faCard.add(cardGC, "cardGC");

        cardNC.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(220, 35));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("NHÂN VIÊN NHẬN CA");
        jPanel10.add(jLabel12);

        cardNC.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel12.setMinimumSize(new java.awt.Dimension(250, 100));
        jPanel12.setLayout(new java.awt.GridLayout(8, 0, 0, 10));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Nhân viên nhận ca:");
        jPanel12.add(jLabel14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Nhân viên giao ca:");
        jPanel12.add(jLabel13);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Thời gian nhận ca:");
        jPanel12.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Tiền duy trì hoạt động:");
        jPanel12.add(jLabel16);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Tiền phát sinh:");
        jPanel12.add(jLabel18);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setText("Doanh thu ca:");
        jPanel12.add(jLabel20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setText("Tổng tiền:");
        jPanel12.add(jLabel19);

        jPanel11.add(jPanel12, java.awt.BorderLayout.LINE_START);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 55, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel14.setLayout(new java.awt.GridLayout(8, 0, 0, 10));

        lblNCcardNVNC.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel14.add(lblNCcardNVNC);

        lblcardNCNVGC.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel14.add(lblcardNCNVGC);

        lblcardNCStartTime.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel14.add(lblcardNCStartTime);

        lblCardNCTienCoSo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel14.add(lblCardNCTienCoSo);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new java.awt.BorderLayout());

        lblCardNCTienPhatSinh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel15.add(lblCardNCTienPhatSinh, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel15);

        lblCardNCDoanhThuCa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel14.add(lblCardNCDoanhThuCa);

        lblCardNCTongTien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel14.add(lblCardNCTongTien);

        jPanel11.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(1090, 250));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 5, 15, new java.awt.Color(255, 255, 255)));
        jPanel17.setPreferredSize(new java.awt.Dimension(1090, 80));
        jPanel17.setLayout(new java.awt.BorderLayout());

        btnCardNCOK.setText("Xác nhận");
        btnCardNCOK.setPreferredSize(new java.awt.Dimension(125, 29));
        btnCardNCOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardNCOKActionPerformed(evt);
            }
        });
        jPanel17.add(btnCardNCOK, java.awt.BorderLayout.LINE_END);

        jPanel13.add(jPanel17, java.awt.BorderLayout.PAGE_END);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setText("Ghi chú:");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel21.setPreferredSize(new java.awt.Dimension(235, 20));
        jLabel21.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel18.add(jLabel21, java.awt.BorderLayout.LINE_START);

        sp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        txtCardNCGhiChu.setColumns(20);
        txtCardNCGhiChu.setRows(5);
        sp.setViewportView(txtCardNCGhiChu);

        jPanel18.add(sp, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel13, java.awt.BorderLayout.SOUTH);

        cardNC.add(jPanel11, java.awt.BorderLayout.CENTER);

        faCard.add(cardNC, "cardNC");

        getContentPane().add(faCard, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTienPhatSinhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTienPhatSinhFocusLost
        // TODO add your handling code here:
        if (!txtTienPhatSinh.getText().isEmpty()) {
            String t = df.format(Double.parseDouble(txtTienPhatSinh.getText()));
            txtTienPhatSinh.setText(t);
        }
        if (df.parse(lblTongTien.getText(), new ParsePosition(0)).doubleValue() < 1000000) {
            if (!Messeger.confirm(null, "Khoản tiền duy trì hoạt động không đủ!")) {
                txtTienPhatSinh.setText("0");
            }
        }
    }//GEN-LAST:event_txtTienPhatSinhFocusLost

    private void txtTienPhatSinhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienPhatSinhKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {
            txtTienPhatSinh.setEditable(true);
        } else if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
            txtTienPhatSinh.setEditable(true);
        } else {
            txtTienPhatSinh.setEditable(false);
        }
    }//GEN-LAST:event_txtTienPhatSinhKeyPressed

    private void txtTienPhatSinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienPhatSinhKeyReleased
        double tongtien;
        if (!txtTienPhatSinh.getText().isEmpty()) {
            if (radChi.isSelected()) {

                tongtien = df.parse(lblTienCS.getText(), new ParsePosition(0)).doubleValue()
                        + df.parse(lblDTCa.getText(), new ParsePosition(0)).doubleValue()
                        - Double.parseDouble(txtTienPhatSinh.getText());

            } else {
                tongtien = df.parse(lblTienCS.getText(), new ParsePosition(0)).doubleValue()
                        + df.parse(lblDTCa.getText(), new ParsePosition(0)).doubleValue()
                        + Double.parseDouble(txtTienPhatSinh.getText());
            }
        } else {
            tongtien = df.parse(lblTienCS.getText(), new ParsePosition(0)).doubleValue()
                    + df.parse(lblDTCa.getText(), new ParsePosition(0)).doubleValue();
        }
        lblTongTien.setText(df.format(tongtien));
        

    }//GEN-LAST:event_txtTienPhatSinhKeyReleased

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        try {
            // TODO add your handling code here:
            if (!txtTienPhatSinh.getText().isEmpty()) {
                if (txtGhiChu.getText().isEmpty()) {
                    Messeger.showErrorDialog(null, "Mời điền lí do phát sinh", "Lỗi");
                    return;
                }
            }
            if (gcDAO.update(setEntityGC())) {
                Messeger.alert(null, "Giao ca thành công!");
                this.dispose();
            } else {
                Messeger.showErrorDialog(null, "Giao ca thất bại!", "Lỗi giao ca");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnOkActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnCardNCOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardNCOKActionPerformed
        try {
            if (gcDAO.updateNC(setEntityNC())) {
                Messeger.alert(null, "Nhận ca thành công!");
                gcDAO.insertAfterGC(new GiaoCa(Auth.user.getMaNV(), df.parse(lblCardNCTongTien.getText(), new ParsePosition(0)).doubleValue()));
                this.dispose();
            } else {
                Messeger.showErrorDialog(null, "Nhận ca thất bại!", "Lỗi giao ca");
            }
        } catch (Exception ex) {
            Logger.getLogger(GiaoCaFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCardNCOKActionPerformed

    private void txtTienPhatSinhFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTienPhatSinhFocusGained
        // TODO add your handling code here:
        if (!txtTienPhatSinh.getText().isEmpty()) {
            txtTienPhatSinh.setText(df.parse(txtTienPhatSinh.getText(), new ParsePosition(0)).toString());
        }
    }//GEN-LAST:event_txtTienPhatSinhFocusGained

    private void radThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radThuActionPerformed
        // TODO add your handling code here:
        double tongtien;
        if(radThu.isSelected()) {
        if (!txtTienPhatSinh.getText().isEmpty()) {

            tongtien = df.parse(lblTienCS.getText(), new ParsePosition(0)).doubleValue()
                    + df.parse(lblDTCa.getText(), new ParsePosition(0)).doubleValue()
                    + df.parse(txtTienPhatSinh.getText(), new ParsePosition(0)).doubleValue();

        } else {
            tongtien = df.parse(lblTienCS.getText(), new ParsePosition(0)).doubleValue()
                    + df.parse(lblDTCa.getText(), new ParsePosition(0)).doubleValue();
        }
        lblTongTien.setText(df.format(tongtien));
        }
    }//GEN-LAST:event_radThuActionPerformed

    private void radChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radChiActionPerformed
        // TODO add your handling code here:
        double tongtien;
        if(radChi.isSelected()) {
        if (!txtTienPhatSinh.getText().isEmpty()) {

            tongtien = df.parse(lblTienCS.getText(), new ParsePosition(0)).doubleValue()
                    + df.parse(lblDTCa.getText(), new ParsePosition(0)).doubleValue()
                    - df.parse(txtTienPhatSinh.getText(), new ParsePosition(0)).doubleValue();

        } else {
            tongtien = df.parse(lblTienCS.getText(), new ParsePosition(0)).doubleValue()
                    + df.parse(lblDTCa.getText(), new ParsePosition(0)).doubleValue();
        }
        lblTongTien.setText(df.format(tongtien));
        if (tongtien < 1000000) {
            if (!Messeger.confirm(null, "Khoản tiền duy trì hoạt động không đủ!")) {
                txtTienPhatSinh.setText("0");
            }
        }
        }
    }//GEN-LAST:event_radChiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoCaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoCaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoCaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoCaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiaoCaFrm dialog = new GiaoCaFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCardNCOK;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cardGC;
    private javax.swing.JPanel cardNC;
    private javax.swing.JComboBox<String> cbxNV;
    private javax.swing.JPanel faCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCardNCDoanhThuCa;
    private javax.swing.JLabel lblCardNCTienCoSo;
    private javax.swing.JLabel lblCardNCTienPhatSinh;
    private javax.swing.JLabel lblCardNCTongTien;
    private javax.swing.JLabel lblDTCa;
    private javax.swing.JLabel lblEndTime;
    private javax.swing.JLabel lblNCcardNVNC;
    private javax.swing.JLabel lblNVGiao;
    private javax.swing.JLabel lblStartTime;
    private javax.swing.JLabel lblTienCS;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblcardNCNVGC;
    private javax.swing.JLabel lblcardNCStartTime;
    private javax.swing.JRadioButton radChi;
    private javax.swing.JRadioButton radThu;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTextArea txtCardNCGhiChu;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtTienPhatSinh;
    // End of variables declaration//GEN-END:variables

    private void init() {
        setLocationRelativeTo(null);

        nvDAO = new NhanVienDao();
        gcDAO = new GiaoCaDAO();
        lst = new ArrayList<>();
        gcCard = (CardLayout) faCard.getLayout();
        fillToCBBNV();
    }

    private void fillToCBBNV() {
        try {
            DefaultComboBoxModel model = (DefaultComboBoxModel) cbxNV.getModel();
            lst = nvDAO.selectAll();
            model.removeAllElements();
            for (NhanVien nhanVien : lst) {

                if (!nhanVien.getMaNV().equals(Auth.user.getMaNV())) {
                    model.addElement(nhanVien);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void setText() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
            lblNVGiao.setText(Auth.user.getHoTen());
            GiaoCa gc = gcDAO.selectById(Auth.user.getMaNV());
            Date pa = sdf.parse(gc.getGioNhanCa());
            maGC = gc.getMaGiaoCa();
            lblStartTime.setText(XDate.toString(pa, "hh:mm dd/MM/yyyy"));
            lblEndTime.setText(XDate.toString(new Date(), "hh:mm dd/MM/yyyy"));
            lblTienCS.setText(df.format(gc.getTienCoSo()));
            lblDTCa.setText(df.format(gc.getDoanhThuCa()));
            lblTongTien.setText(df.format(gc.getDoanhThuCa() + gc.getTienCoSo()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private GiaoCa setEntityGC() {
        try {
            GiaoCa gc = new GiaoCa();
            NhanVien nv = (NhanVien) cbxNV.getSelectedItem();
            String endTime = XDate.toString(XDate.toDate(lblEndTime.getText(), "hh:mm dd/MM/yyyy"), "yyyy-MM-dd hh:mm");

            gc.setMaGiaoCa(maGC);
            gc.setMaNVGiaoCa(Auth.user.getMaNV());
            gc.setGhiChuGC(txtGhiChu.getText());
            gc.setGhiChuNC(txtCardNCGhiChu.getText());
            gc.setMaNVNhan(nv.getMaNV());
            gc.setGioGiaoCa(endTime);
            gc.setTienCoSo(df.parse(lblTienCS.getText(), new ParsePosition(0)).doubleValue());
            if (!txtTienPhatSinh.getText().isEmpty()) {
                if (radChi.isSelected()) {
                    gc.setTienPhatSinh(df.parse(txtTienPhatSinh.getText(), new ParsePosition(0)).doubleValue() * - 1);
                } else {
                    gc.setTienPhatSinh(df.parse(txtTienPhatSinh.getText(), new ParsePosition(0)).doubleValue());
                }
            }else {
                gc.setTienPhatSinh(0);
            }

            gc.setDoanhThuCa(df.parse(lblDTCa.getText(), new ParsePosition(0)).doubleValue());
            gc.setTongTien(df.parse(lblTongTien.getText(), new ParsePosition(0)).doubleValue());
            gc.setMaTT(3);
            return gc;
        } catch (Exception ex) {
            Logger.getLogger(GiaoCaFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    private GiaoCa setEntityNC() {
        try {
            GiaoCa gc = new GiaoCa();
            NhanVien nv = (NhanVien) cbxNV.getSelectedItem();
            gc.setMaGiaoCa(maGC);
            gc.setMaNVGiaoCa(Auth.user.getMaNV());
            gc.setGhiChuNC(txtCardNCGhiChu.getText());
            gc.setMaNVNhan(nv.getMaNV());
            gc.setTienCoSo(df.parse(lblCardNCTienCoSo.getText(), new ParsePosition(0)).doubleValue());
            if (!lblCardNCTienPhatSinh.getText().isEmpty()) {
                gc.setTienPhatSinh(df.parse(lblCardNCTienPhatSinh.getText(), new ParsePosition(0)).doubleValue());
            }
            gc.setDoanhThuCa(df.parse(lblCardNCDoanhThuCa.getText(), new ParsePosition(0)).doubleValue());
            gc.setTongTien(df.parse(lblCardNCTongTien.getText(), new ParsePosition(0)).doubleValue());
            gc.setMaTT(1);
            return gc;
        } catch (Exception ex) {
            Logger.getLogger(GiaoCaFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public boolean nhanCa() {
        try {
            GiaoCa gc = gcDAO.selectByIDNC();
            GiaoCa gc1 = gcDAO.selectById(Auth.user.getMaNV());
            if (gc != null) {
                lblNCcardNVNC.setText(Auth.user.getHoTen());
                for (NhanVien nv : lst) {
                    if (gc.getMaNVGiaoCa().equals(nv.getMaNV())) {
                        lblcardNCNVGC.setText(nv.getHoTen());
                    }
                }
                maGC = gc.getMaGiaoCa();
                lblStartTime.setText(gc.getGioNhanCa());
                lblCardNCTienPhatSinh.setText(df.format(gc.getTienPhatSinh()));
                lblcardNCStartTime.setText(XDate.toString(new Date(), "hh:mm aa dd/MM/yyyy"));
                lblCardNCTienCoSo.setText(df.format(gc.getTienCoSo()));
                lblCardNCDoanhThuCa.setText(df.format(gc.getDoanhThuCa()));
                lblCardNCTongTien.setText(df.format(gc.getTongTien()));

                gcCard.show(faCard, "cardNC");
                return false;
            } else if (gc1 != null) {
                return true;
            } else {
                try {
                    gcDAO.insert(new GiaoCa(Auth.user.getMaNV()));
                } catch (Exception ex) {
                    Logger.getLogger(GiaoCaFrm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(GiaoCaFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }

    public void giaoCa() {
        gcCard.show(faCard, "cardGC");
        setText();

    }

}
