/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.newgui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.plaf.basic.BasicButtonUI;
import poly.dao.GiaoHangDao;
import poly.helper.Auth;
import poly.helper.ImageHelper;
import poly.helper.Messeger;

/**
 *
 * @author NTV
 */
public class NewMainFrm extends javax.swing.JFrame {

    private BanHangFrm bhFrm;
    private QLSPFrm qLSPFrm;
    private GiaoCaFrm gcFrm;
    private QL_CTSPFrm qlCTSPFrm;
    private ThongKeFrm thongKeFrm;
    private QLKMFrm qlKMFrm;
    private QLKhachHangFrm qlKHFrm;
    private QLTaiKhoanFrm qlTaiKhoanFrm;
    private GiaoHangDao daoGH;
    private LichSuGDFrm lichSuGDFrm;
    private QLGiaoCaFrm qlGiaoCaFrm;
    private InforFrm infoFrm;

    /**
     * Creates new form NewMainFrm
     */
    public NewMainFrm() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmMenu = new javax.swing.JPopupMenu();
        mniThongTinCaNhan = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mniQLGiaoCa = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mniQLKH = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniLichSuGD = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniQLSanPham = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniQLChiTietSP = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniThongKe = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniQLKM = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniDangXuat = new javax.swing.JMenuItem();
        pnlHeader = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblTenNV = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblSoLuongDonHang = new javax.swing.JLabel();
        btnGiaoHang_BanHang = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnGC = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnMinimise = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        dpMain = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        pnlFooter = new javax.swing.JPanel();
        btnKhoaManHinh = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnQLTaiKhoan = new javax.swing.JButton();
        btnQLGiaoCa = new javax.swing.JButton();
        btnKhuyenMai = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnQLCTSP = new javax.swing.JButton();
        btnQLSP = new javax.swing.JButton();
        btnQLKhachHang = new javax.swing.JButton();
        btnQLHoaDon = new javax.swing.JButton();

        jpmMenu.setBackground(new java.awt.Color(102, 51, 0));
        jpmMenu.setForeground(new java.awt.Color(255, 255, 255));
        jpmMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpmMenu.setPreferredSize(new java.awt.Dimension(300, 200));

        mniThongTinCaNhan.setBackground(new java.awt.Color(102, 51, 0));
        mniThongTinCaNhan.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mniThongTinCaNhan.setForeground(new java.awt.Color(255, 255, 255));
        mniThongTinCaNhan.setText("Thông Tin cá nhân");
        mniThongTinCaNhan.setOpaque(true);
        mniThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThongTinCaNhanActionPerformed(evt);
            }
        });
        jpmMenu.add(mniThongTinCaNhan);

        jSeparator8.setBackground(new java.awt.Color(102, 51, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator8.setOpaque(true);
        jpmMenu.add(jSeparator8);

        mniQLGiaoCa.setBackground(new java.awt.Color(102, 51, 0));
        mniQLGiaoCa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mniQLGiaoCa.setForeground(new java.awt.Color(255, 255, 255));
        mniQLGiaoCa.setText("Quản lý giao ca");
        mniQLGiaoCa.setOpaque(true);
        mniQLGiaoCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLGiaoCaActionPerformed(evt);
            }
        });
        jpmMenu.add(mniQLGiaoCa);

        jSeparator7.setBackground(new java.awt.Color(102, 51, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOpaque(true);
        jpmMenu.add(jSeparator7);

        mniQLKH.setBackground(new java.awt.Color(102, 51, 0));
        mniQLKH.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mniQLKH.setForeground(new java.awt.Color(255, 255, 255));
        mniQLKH.setText("Quản lý khách hàng");
        mniQLKH.setOpaque(true);
        mniQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLKHActionPerformed(evt);
            }
        });
        jpmMenu.add(mniQLKH);

        jSeparator6.setBackground(new java.awt.Color(102, 51, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setOpaque(true);
        jpmMenu.add(jSeparator6);

        mniLichSuGD.setBackground(new java.awt.Color(102, 51, 0));
        mniLichSuGD.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mniLichSuGD.setForeground(new java.awt.Color(255, 255, 255));
        mniLichSuGD.setText("Lịch sử giao dịch");
        mniLichSuGD.setOpaque(true);
        mniLichSuGD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLichSuGDActionPerformed(evt);
            }
        });
        jpmMenu.add(mniLichSuGD);

        jSeparator5.setBackground(new java.awt.Color(102, 51, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOpaque(true);
        jpmMenu.add(jSeparator5);

        mniQLSanPham.setBackground(new java.awt.Color(102, 51, 0));
        mniQLSanPham.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mniQLSanPham.setForeground(new java.awt.Color(255, 255, 255));
        mniQLSanPham.setText("Quản Lý Sản Phẩm");
        mniQLSanPham.setOpaque(true);
        mniQLSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLSanPhamActionPerformed(evt);
            }
        });
        jpmMenu.add(mniQLSanPham);

        jSeparator1.setBackground(new java.awt.Color(102, 51, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);
        jpmMenu.add(jSeparator1);

        mniQLChiTietSP.setBackground(new java.awt.Color(102, 51, 0));
        mniQLChiTietSP.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mniQLChiTietSP.setForeground(new java.awt.Color(255, 255, 255));
        mniQLChiTietSP.setText("Quản Lý Chi Tiết sản phẩm");
        mniQLChiTietSP.setOpaque(true);
        mniQLChiTietSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLChiTietSPActionPerformed(evt);
            }
        });
        jpmMenu.add(mniQLChiTietSP);

        jSeparator2.setBackground(new java.awt.Color(102, 51, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOpaque(true);
        jpmMenu.add(jSeparator2);

        mniThongKe.setBackground(new java.awt.Color(102, 51, 0));
        mniThongKe.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mniThongKe.setForeground(new java.awt.Color(255, 255, 255));
        mniThongKe.setText("Thống Kê Doanh Thu");
        mniThongKe.setOpaque(true);
        mniThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThongKeActionPerformed(evt);
            }
        });
        jpmMenu.add(mniThongKe);

        jSeparator3.setBackground(new java.awt.Color(102, 51, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOpaque(true);
        jpmMenu.add(jSeparator3);

        mniQLKM.setBackground(new java.awt.Color(102, 51, 0));
        mniQLKM.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mniQLKM.setForeground(new java.awt.Color(255, 255, 255));
        mniQLKM.setText("Quản lý khuyến mại");
        mniQLKM.setOpaque(true);
        mniQLKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLKMActionPerformed(evt);
            }
        });
        jpmMenu.add(mniQLKM);

        jSeparator4.setBackground(new java.awt.Color(102, 51, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOpaque(true);
        jpmMenu.add(jSeparator4);

        mniDangXuat.setBackground(new java.awt.Color(102, 51, 0));
        mniDangXuat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mniDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        mniDangXuat.setText("Đăng Xuất");
        mniDangXuat.setOpaque(true);
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        jpmMenu.add(mniDangXuat);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlHeader.setBackground(new java.awt.Color(0, 0, 0));
        pnlHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 153, 153)));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1068, 50));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setPreferredSize(new java.awt.Dimension(456, 50));
        jPanel6.setLayout(new java.awt.BorderLayout());

        lblTenNV.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTenNV.setForeground(new java.awt.Color(255, 255, 51));
        lblTenNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenNV.setText("Mai Xuân Thành");
        lblTenNV.setToolTipText("Tên Nhân Viên");
        lblTenNV.setPreferredSize(new java.awt.Dimension(290, 17));
        jPanel6.add(lblTenNV, java.awt.BorderLayout.LINE_END);

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setLayout(new java.awt.BorderLayout());

        lblLogo.setBackground(new java.awt.Color(255, 153, 51));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/mainLogo.png"))); // NOI18N
        lblLogo.setPreferredSize(new java.awt.Dimension(250, 12));
        jPanel8.add(lblLogo, java.awt.BorderLayout.LINE_START);

        lblDongHo.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(255, 204, 0));
        lblDongHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDongHo.setText("10");
        jPanel8.add(lblDongHo, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(240, 100));
        jPanel3.setLayout(new java.awt.GridLayout(0, 2, 15, 0));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSoLuongDonHang.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblSoLuongDonHang.setForeground(new java.awt.Color(255, 0, 0));
        lblSoLuongDonHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoLuongDonHang.setText("6");
        jPanel4.add(lblSoLuongDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 20, 30));

        btnGiaoHang_BanHang.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btnGiaoHang_BanHang.setText("Giao Hàng");
        btnGiaoHang_BanHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGiaoHang_BanHang.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGiaoHang_BanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaoHang_BanHangActionPerformed(evt);
            }
        });
        jPanel4.add(btnGiaoHang_BanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel3.add(jPanel4);

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setLayout(new java.awt.BorderLayout());

        btnGC.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btnGC.setText("Giao Ca");
        btnGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGCActionPerformed(evt);
            }
        });
        jPanel7.add(btnGC, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7);

        jPanel8.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        pnlHeader.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 0));
        jPanel5.setLayout(new java.awt.GridLayout(0, 2));

        btnMinimise.setBackground(new java.awt.Color(0, 153, 153));
        btnMinimise.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMinimise.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/mimise32.png"))); // NOI18N
        btnMinimise.setToolTipText("Thu nhỏ");
        btnMinimise.setBorder(null);
        btnMinimise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimiseActionPerformed(evt);
            }
        });
        jPanel5.add(btnMinimise);

        btnClose.setBackground(new java.awt.Color(0, 153, 153));
        btnClose.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/cancel32.png"))); // NOI18N
        btnClose.setToolTipText("Thoát");
        btnClose.setBorder(null);
        btnClose.setHideActionText(true);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel5.add(btnClose);

        pnlHeader.add(jPanel5, java.awt.BorderLayout.EAST);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        dpMain.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(dpMain, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        pnlFooter.setBackground(new java.awt.Color(255, 153, 51));
        pnlFooter.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 4, 4, 4, new java.awt.Color(255, 153, 51)));
        pnlFooter.setPreferredSize(new java.awt.Dimension(1068, 70));
        pnlFooter.setLayout(new java.awt.BorderLayout());

        btnKhoaManHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/lock32.png"))); // NOI18N
        btnKhoaManHinh.setToolTipText("Khóa Màn Hình");
        btnKhoaManHinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoaManHinh.setPreferredSize(new java.awt.Dimension(85, 41));
        btnKhoaManHinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoaManHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaManHinhActionPerformed(evt);
            }
        });
        pnlFooter.add(btnKhoaManHinh, java.awt.BorderLayout.LINE_START);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/menu32.png"))); // NOI18N
        btnMenu.setToolTipText("Hệ Thống");
        btnMenu.setPreferredSize(new java.awt.Dimension(85, 41));
        btnMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        pnlFooter.add(btnMenu, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        btnQLTaiKhoan.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnQLTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnQLTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/man36.png"))); // NOI18N
        btnQLTaiKhoan.setToolTipText("Quản lý tài khoản");
        btnQLTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLTaiKhoan.setPreferredSize(new java.awt.Dimension(173, 65));
        btnQLTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTaiKhoanActionPerformed(evt);
            }
        });
        jPanel2.add(btnQLTaiKhoan);

        btnQLGiaoCa.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnQLGiaoCa.setForeground(new java.awt.Color(255, 255, 255));
        btnQLGiaoCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/GiaoCa36.png"))); // NOI18N
        btnQLGiaoCa.setToolTipText("Quản lí giao ca");
        btnQLGiaoCa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLGiaoCa.setPreferredSize(new java.awt.Dimension(173, 65));
        btnQLGiaoCa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLGiaoCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLGiaoCaActionPerformed(evt);
            }
        });
        jPanel2.add(btnQLGiaoCa);

        btnKhuyenMai.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnKhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        btnKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/sale36.png"))); // NOI18N
        btnKhuyenMai.setToolTipText("Quản Lý Khuyến Mại");
        btnKhuyenMai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhuyenMai.setPreferredSize(new java.awt.Dimension(173, 65));
        btnKhuyenMai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhuyenMaiActionPerformed(evt);
            }
        });
        jPanel2.add(btnKhuyenMai);

        btnThongKe.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/chart_36.png"))); // NOI18N
        btnThongKe.setToolTipText("Thống Kê");
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setPreferredSize(new java.awt.Dimension(173, 65));
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jPanel2.add(btnThongKe);

        btnQLCTSP.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnQLCTSP.setForeground(new java.awt.Color(255, 255, 255));
        btnQLCTSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/size36.png"))); // NOI18N
        btnQLCTSP.setToolTipText("Quản lý chi tiết sản phảm");
        btnQLCTSP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLCTSP.setPreferredSize(new java.awt.Dimension(173, 65));
        btnQLCTSP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLCTSPActionPerformed(evt);
            }
        });
        jPanel2.add(btnQLCTSP);

        btnQLSP.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnQLSP.setForeground(new java.awt.Color(255, 255, 255));
        btnQLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/new-product36.png"))); // NOI18N
        btnQLSP.setToolTipText("Quản lý sản phẩm");
        btnQLSP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLSP.setPreferredSize(new java.awt.Dimension(133, 65));
        btnQLSP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSPActionPerformed(evt);
            }
        });
        jPanel2.add(btnQLSP);

        btnQLKhachHang.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnQLKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnQLKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/customer36.png"))); // NOI18N
        btnQLKhachHang.setToolTipText("Quản lý khách hàng");
        btnQLKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLKhachHang.setPreferredSize(new java.awt.Dimension(133, 65));
        btnQLKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKhachHangActionPerformed(evt);
            }
        });
        jPanel2.add(btnQLKhachHang);

        btnQLHoaDon.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnQLHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnQLHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/budget36.png"))); // NOI18N
        btnQLHoaDon.setToolTipText("Lịch sử giao dịch");
        btnQLHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLHoaDon.setPreferredSize(new java.awt.Dimension(133, 65));
        btnQLHoaDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHoaDonActionPerformed(evt);
            }
        });
        jPanel2.add(btnQLHoaDon);

        pnlFooter.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnlFooter);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnKhoaManHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaManHinhActionPerformed
        new KhoaManHinhFrm(this, true).setVisible(true);
    }//GEN-LAST:event_btnKhoaManHinhActionPerformed

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        jpmMenu.show(btnMenu, -190, -190);
    }//GEN-LAST:event_btnMenuMouseClicked

    private void btnKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhuyenMaiActionPerformed
        openQLKMFrm();
    }//GEN-LAST:event_btnKhuyenMaiActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        openThongKeFrm();
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnQLCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLCTSPActionPerformed
        openQL_CTSPFrm();
    }//GEN-LAST:event_btnQLCTSPActionPerformed

    private void btnQLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSPActionPerformed
        openQLSPFrm();
    }//GEN-LAST:event_btnQLSPActionPerformed

    private void btnQLKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKhachHangActionPerformed
        openKhachHangFrm();
    }//GEN-LAST:event_btnQLKhachHangActionPerformed

    private void btnQLHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHoaDonActionPerformed
        openLichSuGDFrm();
    }//GEN-LAST:event_btnQLHoaDonActionPerformed

    private void mniQLSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLSanPhamActionPerformed
        openQLSPFrm();
    }//GEN-LAST:event_mniQLSanPhamActionPerformed

    private void mniQLChiTietSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLChiTietSPActionPerformed
        openQL_CTSPFrm();
    }//GEN-LAST:event_mniQLChiTietSPActionPerformed

    private void mniThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongKeActionPerformed
        openThongKeFrm();
    }//GEN-LAST:event_mniThongKeActionPerformed

    private void mniQLKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLKMActionPerformed
        openQLKMFrm();
    }//GEN-LAST:event_mniQLKMActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        if (bhFrm.isVisible()) {
            closeAllFrm(false);
        } 
            dpMain.add(bhFrm);
            closeAllFrm(false);
        
        lblTenNV.setText("Chưa đăng nhập");
        new LoginFrm(this, true).setVisible(true);
        phanQuyen();
        new LoadingFrm(this, true, bhFrm.getPnlTabs()).setVisible(true);
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void btnGiaoHang_BanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaoHang_BanHangActionPerformed
        closeAllFrm(true);
        if (bhFrm == null || bhFrm.isClosed()) {
            bhFrm = new BanHangFrm(this);
            dpMain.add(bhFrm);
            bhFrm.showGiaoHang(btnGiaoHang_BanHang);
            bhFrm.setVisible(true);
        } else {
            dpMain.add(bhFrm);
            bhFrm.showGiaoHang(btnGiaoHang_BanHang);
            bhFrm.setVisible(true);

        }

    }//GEN-LAST:event_btnGiaoHang_BanHangActionPerformed

    private void btnGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGCActionPerformed
        // TODO add your handling code here:
        gcFrm = new GiaoCaFrm(this, true);
        gcFrm.giaoCa();
        gcFrm.setVisible(true);
    }//GEN-LAST:event_btnGCActionPerformed

    private void btnMinimiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimiseActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimiseActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        if (Messeger.confirm(this, "Bạn chắc chắn muốn thoát chứ?")) {
            System.exit(0);
        } else {
            return;
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnQLTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTaiKhoanActionPerformed
        openTaiKhoanFrm();
    }//GEN-LAST:event_btnQLTaiKhoanActionPerformed

    private void btnQLGiaoCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLGiaoCaActionPerformed
        openQLGiaoCaFrm();
    }//GEN-LAST:event_btnQLGiaoCaActionPerformed

    private void mniLichSuGDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLichSuGDActionPerformed
        openLichSuGDFrm();
    }//GEN-LAST:event_mniLichSuGDActionPerformed

    private void mniQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLKHActionPerformed
        openKhachHangFrm();
    }//GEN-LAST:event_mniQLKHActionPerformed

    private void mniQLGiaoCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLGiaoCaActionPerformed
        openQLGiaoCaFrm();
    }//GEN-LAST:event_mniQLGiaoCaActionPerformed

    private void mniThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongTinCaNhanActionPerformed
        openThongTinCaNhan();
    }//GEN-LAST:event_mniThongTinCaNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMainFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGC;
    private javax.swing.JButton btnGiaoHang_BanHang;
    private javax.swing.JButton btnKhoaManHinh;
    private javax.swing.JButton btnKhuyenMai;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMinimise;
    private javax.swing.JButton btnQLCTSP;
    private javax.swing.JButton btnQLGiaoCa;
    private javax.swing.JButton btnQLHoaDon;
    private javax.swing.JButton btnQLKhachHang;
    private javax.swing.JButton btnQLSP;
    private javax.swing.JButton btnQLTaiKhoan;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JDesktopPane dpMain;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu jpmMenu;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSoLuongDonHang;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniLichSuGD;
    private javax.swing.JMenuItem mniQLChiTietSP;
    private javax.swing.JMenuItem mniQLGiaoCa;
    private javax.swing.JMenuItem mniQLKH;
    private javax.swing.JMenuItem mniQLKM;
    private javax.swing.JMenuItem mniQLSanPham;
    private javax.swing.JMenuItem mniThongKe;
    private javax.swing.JMenuItem mniThongTinCaNhan;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables

    private void init() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
        //set icon cho app
        this.setIconImage(ImageHelper.getAppIcon());
        daoGH = new GiaoHangDao();
        new LoginFrm(this, true).setVisible(true);
        phanQuyen();
        new LoadingFrm(this, true, bhFrm.getPnlTabs()).setVisible(true);

        startDongHo();
        mouseHover();

    }

    private void closeAllFrm(boolean chon) {
        // TODO add your handling code here:
        if (chon) {
            for (JInternalFrame frame : dpMain.getAllFrames()) {
                if (frame == bhFrm) {
                    dpMain.remove(frame);
                } else {
                    frame.dispose();
                }
            }
        } else {
            for (JInternalFrame frame : dpMain.getAllFrames()) {
                frame.dispose();
            }
        }
    }

    private void mouseHover() {
        //Hiệu ứng di chuột vào các button menu
        JButton[] btns = {btnKhoaManHinh, btnKhuyenMai, btnMenu, btnQLCTSP,
            btnQLKhachHang, btnQLSP, btnQLHoaDon, btnThongKe, btnClose,
            btnMinimise, btnQLTaiKhoan, btnGiaoHang_BanHang, btnGC, btnQLGiaoCa};
        for (JButton btn : btns) {
            if (btn != btnClose && btn != btnMinimise && btn != btnGC && btn != btnGiaoHang_BanHang) {
                btn.setBackground(new Color(255, 153, 51));
            } else if (btn == btnGC | btn == btnGiaoHang_BanHang) {
                btn.setBackground(new Color(255, 255, 51));
            } else {
                btn.setBackground(new Color(0, 153, 153));
            }
            if (btn != btnGC && btn != btnGiaoHang_BanHang) {
                btn.setUI(new BasicButtonUI());
            }
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    Cursor cursor = new Cursor(Cursor.HAND_CURSOR); // HAND CURSOR
                    setCursor(cursor);
                    if (btn != btnClose && btn != btnMinimise && btn != btnGC && btn != btnGiaoHang_BanHang) {
                        btn.setBackground(new Color(0, 153, 153));
                    } else {
                        btn.setBackground(new Color(255, 153, 51));
                    }
                    if (btn != btnGC && btn != btnGiaoHang_BanHang) {
                        btn.setHorizontalAlignment(SwingConstants.CENTER);
                    }
                    if (btn == btnKhuyenMai) {
                        btn.setText("Quản lý khuyến mại");
                    } else if (btn == btnQLCTSP) {
                        btn.setText("Quản lý chi tiết sản phẩm");
                    } else if (btn == btnQLKhachHang) {
                        btn.setText("Quản lý khách hàng");
                    } else if (btn == btnQLSP) {
                        btn.setText("Quản lý sản phẩm");
                    } else if (btn == btnQLHoaDon) {
                        btn.setText("Lịch sử giao dịch");
                    } else if (btn == btnThongKe) {
                        btn.setText("Thống Kê");
                    } else if (btn == btnQLTaiKhoan) {
                        btn.setText("Quản lý tài khoản");
                    } else if (btn == btnQLGiaoCa) {
                        btn.setText("Quản lý Giao ca");
                    }
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    Cursor cursor = new Cursor(Cursor.DEFAULT_CURSOR); // HAND CURSOR
                    setCursor(cursor);
                    if (btn != btnClose && btn != btnMinimise && btn != btnGC && btn != btnGiaoHang_BanHang) {
                        btn.setBackground(new Color(255, 153, 51));
                    } else if (btn == btnGC | btn == btnGiaoHang_BanHang) {
                        btn.setBackground(new Color(255, 255, 51));
                    } else {
                        btn.setBackground(new Color(0, 153, 153));
                    }

                    if (btn != btnKhoaManHinh && btn != btnMenu && btn != btnGC && btn != btnGiaoHang_BanHang) {
                        btn.setText("");
                    }
                }
            });
        }
    }

    private void startDongHo() {
        //Hiển thị đồng hồ
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat fm = new SimpleDateFormat("hh:mm:ss a");
                String txt = fm.format(now);
                lblDongHo.setText(txt);
            }
        }).start();
    }

    public void phanQuyen() {
        setLblTenNV();
        openBanHangFrm();
        if (Auth.user.getVaiTro() != 101) {
            btnQLGiaoCa.setVisible(false);
            btnQLTaiKhoan.setVisible(false);
            btnThongKe.setVisible(false);
            btnQLHoaDon.setVisible(false);
            mniThongKe.setVisible(false);
            mniLichSuGD.setVisible(false);
            mniQLGiaoCa.setVisible(false);
        } else {
            btnQLGiaoCa.setVisible(true);
            btnQLTaiKhoan.setVisible(true);
            btnThongKe.setVisible(true);
            btnQLHoaDon.setVisible(true);
            mniThongKe.setVisible(true);
            mniLichSuGD.setVisible(true);
            mniQLGiaoCa.setVisible(true);
        }
        this.setLblSoLuongDonHang();
    }

    public void setLblTenNV() {
        if (Auth.user == null) {
            this.lblTenNV.setText("Chưa đăng nhập");
        } else {
            this.lblTenNV.setText(Auth.user.getHoTen());
        }
    }

    public void setLblSoLuongDonHang() {
        lblSoLuongDonHang.setText(this.daoGH.getHDDangGiao() + "");
    }

    private void openQLSPFrm() {
        closeAllFrm(true);
        if (qLSPFrm == null || qLSPFrm.isClosed()) {
            qLSPFrm = new QLSPFrm(this);
            dpMain.add(qLSPFrm);
            qLSPFrm.setVisible(true);
        } else {
            qLSPFrm.setVisible(true);
        }
    }

    private void openBanHangFrm() {
        closeAllFrm(true);
        if (bhFrm == null || bhFrm.isClosed()) {
            bhFrm = new BanHangFrm(this);
            dpMain.add(bhFrm);
            bhFrm.setVisible(true);
        } else {
            dpMain.add(bhFrm);
            bhFrm.setVisible(true);
        }
    }

    private void openQL_CTSPFrm() {
        closeAllFrm(true);
        if (qlCTSPFrm == null || qlCTSPFrm.isClosed()) {
            qlCTSPFrm = new QL_CTSPFrm(this);
            dpMain.add(qlCTSPFrm);
            qlCTSPFrm.setVisible(true);
        } else {
            qlCTSPFrm.setVisible(true);
        }
    }

    private void openQLKMFrm() {
        closeAllFrm(true);
        if (qlKMFrm == null || qlKMFrm.isClosed()) {
            qlKMFrm = new QLKMFrm(this);
            dpMain.add(qlKMFrm);
            qlKMFrm.setVisible(true);
        } else {
            qlKMFrm.setVisible(true);
        }
    }

    private void openThongKeFrm() {
        closeAllFrm(true);
        if (thongKeFrm == null || thongKeFrm.isClosed()) {
            thongKeFrm = new ThongKeFrm(dpMain);
            dpMain.add(thongKeFrm);
            thongKeFrm.setVisible(true);
        } else {
            thongKeFrm.setVisible(true);
        }
    }

    private void openKhachHangFrm() {
        closeAllFrm(true);
        if (qlKHFrm == null || qlKHFrm.isClosed()) {
            qlKHFrm = new QLKhachHangFrm();
            dpMain.add(qlKHFrm);
            qlKHFrm.setVisible(true);
        } else {
            qlKHFrm.setVisible(true);
        }
    }

    private void openTaiKhoanFrm() {
        closeAllFrm(true);
        if (qlTaiKhoanFrm == null || qlTaiKhoanFrm.isClosed()) {
            qlTaiKhoanFrm = new QLTaiKhoanFrm();
            dpMain.add(qlTaiKhoanFrm);
            qlTaiKhoanFrm.setVisible(true);
        } else {
            qlTaiKhoanFrm.setVisible(true);
        }
    }

    private void openLichSuGDFrm() {
        closeAllFrm(true);
        if (lichSuGDFrm == null || lichSuGDFrm.isClosed()) {
            lichSuGDFrm = new LichSuGDFrm();
            dpMain.add(lichSuGDFrm);
            lichSuGDFrm.setVisible(true);
        } else {
            lichSuGDFrm.setVisible(true);
        }
    }

    private void openQLGiaoCaFrm() {
        closeAllFrm(true);
        if (qlGiaoCaFrm == null || qlGiaoCaFrm.isClosed()) {
            qlGiaoCaFrm = new QLGiaoCaFrm();
            dpMain.add(qlGiaoCaFrm);
            qlGiaoCaFrm.setVisible(true);
        } else {
            qlGiaoCaFrm.setVisible(true);
        }
    }

    private void openThongTinCaNhan() {
        closeAllFrm(true);
        if (infoFrm == null || infoFrm.isClosed()) {
            infoFrm = new InforFrm(this);
            dpMain.add(infoFrm);
            infoFrm.setVisible(true);
        } else {
            infoFrm.setVisible(true);
        }
    }

}
