          /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import DomainModels.DanhMuc;
import DomainModels.HoaDon;
import DomainModels.HoaDonChiTiet;
import DomainModels.Hoadonct_SanpCT_Sp;
import DomainModels.SanPham;
import Services.ChiTietSanPhamService;
import Services.DanhMucService;
import Services.HoaDonChiTieservice;
import Services.KhachHangService;
import Services.SanPhamService;
import Services.hoadonservice;
import ViewModels.ChiTietSanPhamModel;
import ViewModels.DanhMucModel;
import ViewModels.HoaDonViewModel;
import ViewModels.KhachHangModel;
import ViewModels.hoadonchitietviewmodel;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phanh
 */
public class BanHangJPanel extends javax.swing.JPanel {

    CardLayout cardlayout;
    private ChiTietSanPhamService CTSPService;
    private SanPhamService spser;
    private KhachHangService khservice;
    private hoadonservice hdsv;
    boolean isSanPhamSelected = true;
    private HoaDonChiTieservice hdct;
    
//    private HoaDonChiTiet
    DefaultTableModel modelTable = new DefaultTableModel();
    int stt = 0;
    int slNhap;
    int slGoc;
    int maxMaHD;
//    private hoa hd;
    JTabbedPane pnlTabs;
    DefaultTableModel dtmHoaDon=new DefaultTableModel();
    Locale localeVN = new Locale("vi", "VN");
    NumberFormat df = NumberFormat.getCurrencyInstance(localeVN);
    DefaultComboBoxModel<DanhMucModel> CBBModelDM;
    DanhMucService dmsv;
    
    /**
     * Creates new form BanHangJPanel
     */
    public BanHangJPanel() {
        initComponents();
        dmsv = new DanhMucService();
        
        CTSPService = new ChiTietSanPhamService();
        khservice = new KhachHangService();
        spser = new SanPhamService();
        khservice=new KhachHangService();
       
        hdct=new HoaDonChiTieservice();
        hdsv=new hoadonservice();
          
        this.pnlTabs = pnlTabs;
        loadTableBanHang(CTSPService.getAllChiTietSanPham());
        loadTableThongTin();
//        loadhoadon();
        

    }
//  public  void loadhoadon(){
//      ArrayList<HoaDon> list=hdsv.getAllhoadon();
//      modelTable=(DefaultTableModel) tblHoadon.getModel();
//      modelTable.setRowCount(0);
//      for (HoaDon hd : list) {
//          modelTable.addRow(new Object[]{
//              hd.getMahd(),
//              hd.getIdNV(),
//              hd.getIdKH(),
//              hd.getIdKM(),
//              hd.getNgayTao(),
//              hd.getTrangThai()== 1 ? "Đã thanh toán" : "Chờ thanh toán"
//          });
//      }
//  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loadTableBanHang(ArrayList<ChiTietSanPhamModel> list) {
        modelTable = (DefaultTableModel) tblBanHang.getModel();
        modelTable.setRowCount(0);
        for (ChiTietSanPhamModel ctspM : list) {
            modelTable.addRow(new Object[]{
                ctspM.getIdCTSP(),
                ctspM.getIdSP(),
          
                ctspM.getGiaBan(),
                ctspM.getSoLuong(),
                ctspM.getIdSize(),
                ctspM.getIdDC(),
                ctspM.getIdCL(),
                ctspM.getIdMS(),
                ctspM.getIdDM(),
                ctspM.getMota()
            });
        }
    }

    private void loadTableBanHang(SanPham sp) {
        ArrayList<ChiTietSanPhamModel> list = new ArrayList<>();
        modelTable = (DefaultTableModel) tblBanHang.getModel();
        modelTable.setRowCount(0);
        for (ChiTietSanPhamModel ctspM : list) {
            modelTable.addRow(new Object[]{ctspM.getIdCTSP(),
                ctspM.getIdSP(),
                ctspM.getIdCTSP(),
                ctspM.getGiaBan(),
                ctspM.getSoLuong(),
                ctspM.getIdSize(),
                ctspM.getIdDC(),
                ctspM.getIdCL(),
                ctspM.getIdMS(),
                ctspM.getIdDM(),
                ctspM.getMota()
            });
        }
    }

   private void loadTableThongTin() {
             ArrayList<HoaDonViewModel> list = hdsv.getAllhoadon();
        modelTable = (DefaultTableModel) tblhoadon.getModel();
        modelTable.setRowCount(0);
        for (HoaDonViewModel HoaDonViewModel : list) {
            modelTable.addRow(new Object[]{
                HoaDonViewModel.getMahd(),
               HoaDonViewModel.getIdKH(),
                HoaDonViewModel.getIdNV(),
                HoaDonViewModel.getNgaymua(),
                HoaDonViewModel.getTrangThai()==0?"Chờ thanh toán":"Đã thanh toán"
            });
        }
        }

 
    public void loadGioHang(ArrayList<Hoadonct_SanpCT_Sp> list) {
        modelTable = (DefaultTableModel) tblGioHang.getModel();
        modelTable.setRowCount(0);
        stt = 1;
        for (Hoadonct_SanpCT_Sp ctsp : list) {
            modelTable.addRow(new Object[]{
                stt,
               ctsp.getTenSP(),
               ctsp.getSl(),
               ctsp.getDonGia(),
                new BigDecimal(ctsp.getSl()* Double.parseDouble(ctsp.getDonGia().toString()))
            });
            stt++;
        }

    }
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnSanpham = new javax.swing.JButton();
        btnKhBh = new javax.swing.JButton();
        txtTimKiemBH = new javax.swing.JTextField();
        btnTimKiemBH = new javax.swing.JButton();
        btnQuetSp = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbltongtien = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        lbltenkh = new javax.swing.JLabel();
        lblhoadontrong = new javax.swing.JLabel();
        pncardgoc = new javax.swing.JPanel();
        Khach = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblhoadon = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtmakhachhang = new javax.swing.JTextField();
        txttenkhachhang = new javax.swing.JTextField();
        txtloaikhachhang = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        txtgioitinh = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        txtngaythamgia = new javax.swing.JTextField();
        txttrangthai = new javax.swing.JTextField();
        Sanpham = new javax.swing.JScrollPane();
        tblBanHang = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1320, 639));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSanpham.setText("Sản Phẩm");
        btnSanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanphamActionPerformed(evt);
            }
        });

        btnKhBh.setText("Khách Hàng");
        btnKhBh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhBhActionPerformed(evt);
            }
        });

        txtTimKiemBH.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemBHCaretUpdate(evt);
            }
        });
        txtTimKiemBH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemBHFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemBHFocusLost(evt);
            }
        });

        btnTimKiemBH.setText("Tìm  Kiếm");
        btnTimKiemBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemBHActionPerformed(evt);
            }
        });

        btnQuetSp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/barcode-scan.png"))); // NOI18N
        btnQuetSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuetSpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKhBh, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiemBH, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiemBH, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(btnQuetSp))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnKhBh, btnSanpham});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnKhBh, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnTimKiemBH, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(txtTimKiemBH)))
                .addGap(7, 7, 7))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuetSp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnKhBh, btnSanpham});

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbltongtien.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbltongtien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltongtien.setText("0");

        txtThanhTien.setText("Thành Tiền");
        txtThanhTien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtThanhTienFocusGained(evt);
            }
        });

        jLabel6.setText("-");

        jButton11.setText("Thanh Toán");

        jButton12.setText("Hóa Đơn Mới");

        jButton13.setText("Xóa Đơn Hàng");
        jButton13.setPreferredSize(new java.awt.Dimension(111, 22));

        jButton14.setText("Đặt Hàng");
        jButton14.setPreferredSize(new java.awt.Dimension(111, 22));

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sản Phẩm", "Số Lượng ", "Đơn Giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGioHang);

        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lbltenkh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbltenkh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltenkh.setText("Khách Lẻ");

        lblhoadontrong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblhoadontrong.setText("Hóa Đơn Trống");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lbltenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(lblhoadontrong, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbltongtien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbltenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhoadontrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(lbltongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton12, jButton13});

        pncardgoc.setLayout(new java.awt.CardLayout());

        tblhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HD", "Mã KH", "Mã NV", "Ngày mua", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhoadonMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblhoadon);
        if (tblhoadon.getColumnModel().getColumnCount() > 0) {
            tblhoadon.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel2.setText("Mã khách hàng");

        jLabel7.setText("Ten khách hàng");

        jLabel8.setText("Loại khách hàng");

        jLabel9.setText("Địa chỉ");

        jLabel10.setText("Giới tính ");

        jLabel11.setText("Email");

        jLabel12.setText("SDT");

        jLabel13.setText("Ngày Sinh");

        jLabel14.setText("Ngày tham gia");

        jLabel15.setText("Trạng thái");

        txtmakhachhang.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtmakhachhangCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmakhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(txttenkhachhang)
                    .addComponent(txtloaikhachhang)
                    .addComponent(txtdiachi)
                    .addComponent(txtgioitinh))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsdt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtngaysinh)
                            .addComponent(txtngaythamgia)
                            .addComponent(txttrangthai, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtdiachi, txtemail, txtgioitinh, txtloaikhachhang, txtmakhachhang, txtngaysinh, txtngaythamgia, txtsdt, txttenkhachhang, txttrangthai});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(txtmakhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(txttenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(txtloaikhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngaythamgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(txtgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtdiachi, txtemail, txtgioitinh, txtloaikhachhang, txtmakhachhang, txtngaysinh, txtngaythamgia, txtsdt, txttenkhachhang, txttrangthai});

        javax.swing.GroupLayout KhachLayout = new javax.swing.GroupLayout(Khach);
        Khach.setLayout(KhachLayout);
        KhachLayout.setHorizontalGroup(
            KhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhachLayout.createSequentialGroup()
                .addGroup(KhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KhachLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        KhachLayout.setVerticalGroup(
            KhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KhachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pncardgoc.add(Khach, "khach");

        tblBanHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IDCTSP", "Mã SP", "Giá Bán", "Số Lượng", "Size", "Độ Cao", "Chất Liệu", "Màu Sắc", "Danh Mục", "Mô Tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanHangMouseClicked(evt);
            }
        });
        Sanpham.setViewportView(tblBanHang);

        pncardgoc.add(Sanpham, "sanpham");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pncardgoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 172, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(pncardgoc, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhBhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhBhActionPerformed
        CardLayout layout = (CardLayout) pncardgoc.getLayout();
        layout.show(pncardgoc, "khach");
        this.isSanPhamSelected = false;
        changeBackgroud_SP_KH();
    }//GEN-LAST:event_btnKhBhActionPerformed

    private void btnSanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanphamActionPerformed
        CardLayout layout = (CardLayout) pncardgoc.getLayout();
        layout.show(pncardgoc, "sanpham");
        this.isSanPhamSelected = true;
        changeBackgroud_SP_KH();
    }//GEN-LAST:event_btnSanphamActionPerformed

    private void txtTimKiemBHCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemBHCaretUpdate
        if (txtTimKiemBH.getText().equalsIgnoreCase("Tìm Kiếm Khách Hàng") || txtTimKiemBH.getText().equalsIgnoreCase("Tìm Kiếm Sản Phẩm")) {
            txtTimKiemBH.setText("");
            txtTimKiemBH.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtTimKiemBHCaretUpdate

    private void btnTimKiemBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemBHActionPerformed

        if (isSanPhamSelected == true) {
            if (txtTimKiemBH.getText().equalsIgnoreCase("Tìm Kiếm Sản Phẩm")) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Tên hoặc mã sản phẩm");
                return;
            }
            String maSP = txtTimKiemBH.getText();
            ArrayList<ChiTietSanPhamModel> listSP = CTSPService.getChiTietSanPhamByDanhMuc(maSP);
            loadTableBanHang(listSP);
        } else {
            if (txtTimKiemBH.getText().equalsIgnoreCase("Tìm Kiếm Khách Hàng")) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Tên hoặc mã khách hàng");
                return;
            }
            String makh = txtTimKiemBH.getText();
            KhachHangModel listSP = khservice.gettheomakh(makh);
            loadTableThongTin();
        }


    }//GEN-LAST:event_btnTimKiemBHActionPerformed

    private void txtTimKiemBHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemBHFocusLost
        if (txtTimKiemBH.getText().trim().isEmpty()) {
            txtTimKiemBH.setForeground(new Color(255, 0, 0));
            changeBackgroud_SP_KH();
        }
    }//GEN-LAST:event_txtTimKiemBHFocusLost

    

    private void tblhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhoadonMouseClicked
  int row = tblhoadon.getSelectedRow();
        if (row < 0) {
            return;
        }
        String maHD = tblhoadon.getValueAt(row, 0).toString();
        String makh=tblhoadon.getValueAt(row, 1).toString();
        
     
        txtmakhachhang.setText(makh);
   

        ArrayList<Hoadonct_SanpCT_Sp> li = hdct.gettheoMAhd(maHD);
        loadGioHang(li);
        double tongTien = 0;
        for (Hoadonct_SanpCT_Sp hoaDonChiTiet : li) {
            tongTien += hoaDonChiTiet.getSl() * Double.parseDouble(hoaDonChiTiet.getDonGia().toString());

        }
        lbltongtien.setText(new BigDecimal(tongTien) + ""); 
        txtThanhTien.setText(new BigDecimal(tongTien) + ""); 
    }//GEN-LAST:event_tblhoadonMouseClicked

    private void tblBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanHangMouseClicked
  int row1 = tblhoadon.getSelectedRow();
        if (row1 < 0) {
            JOptionPane.showMessageDialog(this, "Ban khong chon hoa don nao !");
            return;
        }

        Hoadonct_SanpCT_Sp hdct_ = new Hoadonct_SanpCT_Sp();
        int row = tblBanHang.getSelectedRow();
        if (row < 0) {

            return;
        }

        String maSP = tblBanHang.getValueAt(row, 1).toString();
        String maHD = tblhoadon.getValueAt(row1, 0).toString();
       
        ArrayList<Hoadonct_SanpCT_Sp> li = hdct.gettheoMAhd(maHD);
        HoaDonChiTiet hdct1 = new HoaDonChiTiet();
      
        hdct1.setIdHD(hdct.gettheoidhd(maHD));
        hdct1.setIdCTSP(CTSPService.getChiTietSanPhamByidkmd(maHD));

        hdct1.setDonGia((BigDecimal) tblBanHang.getValueAt(row, 2));
        hdct1.setSoLuong(1);
        for (Hoadonct_SanpCT_Sp h : li) {
            if (h.getMaSP().equalsIgnoreCase(maSP)) {
                hdct1.setSoLuong(h.getSl() + 1);
                hdct.updateKhachHang(hdct1);
                loadGioHang(hdct.gettheoMAhd(maHD));
                ArrayList<Hoadonct_SanpCT_Sp> li2 = hdct.gettheoMAhd(maHD);
                double tongTien = 0;
                for (Hoadonct_SanpCT_Sp hoaDonChiTiet_ChiTietSP_SPham : li2) {
                    tongTien += hoaDonChiTiet_ChiTietSP_SPham.getSl() * Double.parseDouble(hoaDonChiTiet_ChiTietSP_SPham.getDonGia().toString());

                }
                txtThanhTien.setText(new BigDecimal(tongTien) + "");
                return;
            }

        }
        hoadonchitietviewmodel hd=hdct.inserthdct(hdct1);
        if (hd!=null) {
            loadGioHang(hdct.gettheoMAhd(maHD));
        }
        ArrayList<Hoadonct_SanpCT_Sp> li2 = hdct.gettheoMAhd(maHD);
        double tongTien = 0;
        for (Hoadonct_SanpCT_Sp hoaDonChiTiet_ChiTietSP_SPham : li2) {
            tongTien += hoaDonChiTiet_ChiTietSP_SPham.getSl() * Double.parseDouble(hoaDonChiTiet_ChiTietSP_SPham.getDonGia().toString());

        }
        txtThanhTien.setText(new BigDecimal(tongTien) + "");
    
    }//GEN-LAST:event_tblBanHangMouseClicked

    private void txtTimKiemBHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemBHFocusGained
    
    }//GEN-LAST:event_txtTimKiemBHFocusGained


   
    private void btnQuetSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuetSpActionPerformed
        new QRCode().setVisible(true);
    }//GEN-LAST:event_btnQuetSpActionPerformed

    


                                         

    private void txtThanhTienFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtThanhTienFocusGained
        txtThanhTien.setText("");
    }//GEN-LAST:event_txtThanhTienFocusGained

    private void txtmakhachhangCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtmakhachhangCaretUpdate
         // TODO add your handling code here:
//        String MASP = txtmakhachhang.getText();
//       KhachHangModel listSP = khservice.gettheomakh(MASP);
//       
//           this.txtmakhachhang.setText(listSP.getMaKH());
//            this.txttenkhachhang.setText(listSP.getTenKH());
//            this.txtdiachi.setText(listSP.getDiaChi());
//            this.txtgioitinh.setText(listSP.getGioiTinh());
//            this.txtemail.setText(listSP.getEmail());
//            this.txtsdt.setText(listSP.getSdt());
//           this.txtngaysinh.setText(String.valueOf(listSP.getNgaySinh()));
//              this.txtngaythamgia.setText(String.valueOf(listSP.getNgayThamGia()));
//                this.txtngaythamgia.setText(String.valueOf(listSP.getNgayThamGia()));
        
    }//GEN-LAST:event_txtmakhachhangCaretUpdate

   
    private void changeBackgroud_SP_KH() {
        if (isSanPhamSelected == true) {
            btnSanpham.setBackground(new Color(153, 255, 153));

            txtTimKiemBH.setText("Tìm Kiếm Sản Phẩm");
        } else {
            btnKhBh.setBackground(new Color(255, 204, 102));

            txtTimKiemBH.setText("Tìm Kiếm Khách Hàng");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Khach;
    private javax.swing.JScrollPane Sanpham;
    private javax.swing.JButton btnKhBh;
    private javax.swing.JButton btnQuetSp;
    private javax.swing.JButton btnSanpham;
    private javax.swing.JButton btnTimKiemBH;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel jpanel;
    private javax.swing.JLabel lblhoadontrong;
    private javax.swing.JLabel lbltenkh;
    private javax.swing.JLabel lbltongtien;
    private javax.swing.JPanel pncardgoc;
    private javax.swing.JTable tblBanHang;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblhoadon;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTimKiemBH;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtgioitinh;
    private javax.swing.JTextField txtloaikhachhang;
    private javax.swing.JTextField txtmakhachhang;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtngaythamgia;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttenkhachhang;
    private javax.swing.JTextField txttrangthai;
    // End of variables declaration//GEN-END:variables
 
}
