/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DomainModels.HoaDon;
import DomainModels.HoaDonChiTiet;
import Services.ChiTietSanPhamService;
import Services.HoaDonChiTieservice;
import Services.KhuyenMaiService;
import Services.hoadonservice;
import Utilities.DBConnection;
import ViewModels.ChiTietSanPhamModel;
import ViewModels.HoaDonViewModel;
import ViewModels.KhuyenMaiModel;
import ViewModels.hoadonchitietviewmodel;
import java.util.ArrayList;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Asus
 */
public class ThanhToanHoaDonJFrame extends javax.swing.JFrame {

    HoaDonChiTieservice hoaDonChiTieservice = new HoaDonChiTieservice();
    ChiTietSanPhamService chiTietSanPhamService = new ChiTietSanPhamService();
    hoadonservice hoaDonService = new hoadonservice();
    KhuyenMaiService kms = new KhuyenMaiService();
    JPanel banHang;
    HoaDon hd;
    
    /**
     * Creates new form ThanhToanHoaDonJFrame
     */
    public ThanhToanHoaDonJFrame(JPanel banHang, HoaDon hd) {
        initComponents();
        lblTongtien.setText(hd.getThanhTien().toString());
        this.banHang = banHang;
        this.hd = hd;
        
        txtVoucher.setText(Voucher.voucher);
        txtDiem.setText(""+hd.getIdKH().getDiemEXP());
    }

    private KhuyenMaiModel getKhuyenMai(String ma) {
        ArrayList<KhuyenMaiModel> list = kms.getAllKhuyenMai();
        for (KhuyenMaiModel km : list) {
            if (km.getMaKM().equals(ma)) {
                return km;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTongtien = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGiam = new javax.swing.JTextField();
        txtVoucher = new javax.swing.JTextField();
        txtDiem = new javax.swing.JTextField();
        txtTienKH = new javax.swing.JTextField();
        txtTienThoi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        btnThanhToanVaIn = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THANH TOÁN HÓA ĐƠN");

        lblTongtien.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        lblTongtien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongtien.setText("200000");

        jLabel3.setText("Giảm Giá");

        jLabel4.setText("Voucher");

        jLabel5.setText("Point");

        jLabel6.setText("Tiền Khách Trả");

        jLabel7.setText("Trả Lại Khách");

        txtGiam.setText("0");
        txtGiam.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtGiamCaretUpdate(evt);
            }
        });
        txtGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamActionPerformed(evt);
            }
        });

        txtVoucher.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtVoucherCaretUpdate(evt);
            }
        });
        txtVoucher.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtVoucherInputMethodTextChanged(evt);
            }
        });

        txtTienKH.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTienKHCaretUpdate(evt);
            }
        });

        txtTienThoi.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTienThoiCaretUpdate(evt);
            }
        });

        jButton1.setText("Áp Dụng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sử Dụng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnThanhToanVaIn.setText("Thanh Toán + In");
        btnThanhToanVaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanVaInActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTienThoi, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(txtTienKH, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnThanhToan)
                .addGap(149, 149, 149)
                .addComponent(btnThanhToanVaIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHuy)
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTongtien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTienKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTienThoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhToan)
                    .addComponent(btnThanhToanVaIn)
                    .addComponent(btnHuy))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Voucher(this, true).setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtVoucherInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtVoucherInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVoucherInputMethodTextChanged

    private void txtVoucherCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtVoucherCaretUpdate
//        KhuyenMaiModel km=getKhuyenMai(txtVoucher.getText());
//        BigDecimal gia=new BigDecimal(lblTongtien.getText());
//        txtGiam.setText(String.valueOf(km.getGiaTri().doubleValue()*gia.doubleValue()/100));
//        if (txtVoucher.getText().length() == 0) {
//            return;
//        }
//        txtGiam.setText(String.valueOf(Integer.parseInt(lblTongtien.getText()) * Integer.parseInt(txtVoucher.getText()) / 100));
    }//GEN-LAST:event_txtVoucherCaretUpdate

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double diem = Double.valueOf(txtDiem.getText());
        txtGiam.setText(diem + Double.parseDouble(txtGiam.getText()) + "");
        txtDiem.setText("0");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnThanhToanVaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanVaInActionPerformed
        try {
            Hashtable map = new Hashtable();
            JasperReport rpt;

            rpt = JasperCompileManager.compileReport("src\\Views\\rptHoaDon.jrxml");

            map.put("MaHD", hd.getMaHD());

            JasperPrint p = JasperFillManager.fillReport(rpt, map, DBConnection.getConnection());

            JasperViewer.viewReport(p, false);

        } catch (JRException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnThanhToanVaInActionPerformed

    private void txtTienThoiCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTienThoiCaretUpdate

    }//GEN-LAST:event_txtTienThoiCaretUpdate

    private void txtTienKHCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTienKHCaretUpdate
        float tienKh = 0;
        float tienThoi = 0;
        if (txtTienKH.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời bạn nhập số tiền cần thanh toán");
            return;
        }
        tienKh = Float.valueOf(txtTienKH.getText());
        float tongTien = Float.valueOf(lblTongtien.getText());
        if (tienKh >= tongTien) {
            tienThoi = tienKh - tongTien;
        }
        txtTienThoi.setText(String.valueOf(tienThoi));
    }//GEN-LAST:event_txtTienKHCaretUpdate

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        if (Float.valueOf(txtTienKH.getText()) < Float.valueOf(lblTongtien.getText())) {
            JOptionPane.showMessageDialog(this, "Chưa đủ điều kiện thanh toán");
            return;
        }
        ArrayList<HoaDonChiTiet> listHDCT = hoaDonChiTieservice.getAllhoadon();
        ArrayList<HoaDonChiTiet> listNewHDCT = new ArrayList<>();
        hoadonchitietviewmodel hdctvm = new hoadonchitietviewmodel();
        ChiTietSanPhamModel ctsp = new ChiTietSanPhamModel();

        HoaDonViewModel h = new HoaDonViewModel();
        h.setThanhTien(hd.getThanhTien());
        h.setMaHD(hd.getMaHD());
        if (hoaDonService.updateHoaDon_ThanhToan(h) != null) {
            for (HoaDonChiTiet x : listHDCT) {
                if (x.getIdHD() != null && x.getIdHD().getMaHD().equals(hd.getMaHD())) {
                    listNewHDCT.add(x);
                }
            }
            for (HoaDonChiTiet y : listNewHDCT) {
                hdctvm.setIdHD(y.getIdHD());
                ctsp.setIdCTSP(y.getIdCTSP().getIdCTSP());
                ctsp.setSoLuong(y.getSoLuong());
                chiTietSanPhamService.update_ThanhToan(ctsp);
            }
            hoaDonChiTieservice.updateHDCT_ThanhToan(hdctvm);
            JOptionPane.showMessageDialog(this, "Thanh toán thành công");

        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void txtGiamCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtGiamCaretUpdate
        String chuaGiam = lblTongtien.getText();
        if (txtGiam.getText().trim().isEmpty()) {
            lblTongtien.setText(hd.getThanhTien().toString());
        } else {
            float giamGia = Float.valueOf(txtGiam.getText());
            float tongTien = Float.valueOf(hd.getThanhTien().toString());
            String sauGiam = String.valueOf(tongTien - giamGia);
            lblTongtien.setText(sauGiam);
        }

    }//GEN-LAST:event_txtGiamCaretUpdate

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
       HoaDonViewModel hdHuy = new HoaDonViewModel();
       hdHuy.setMaHD(hd.getMaHD());
       String lydo=JOptionPane.showInputDialog(this, "Vui lòng nhập lý do hủy?");
       hdHuy.setGhiChu(lydo);
       if(hoaDonService.updateHoaDon_HUY(hdHuy)!=null){
          JOptionPane.showMessageDialog(this, "Hủy hóa đơn thành công");
       }
        
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToanHoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToanHoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToanHoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToanHoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ThanhToanHoaDonJFrame().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ThanhToanHoaDonJFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThanhToanVaIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTongtien;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtGiam;
    private javax.swing.JTextField txtTienKH;
    private javax.swing.JTextField txtTienThoi;
    private javax.swing.JTextField txtVoucher;
    // End of variables declaration//GEN-END:variables
}
