USE ORANGESYS
GO
-- Bảng câu truy vấn dữ liệu

-- Bảng VAITRO
/*
	DELETE FROM VAITRO WHERE (MAVAITRO = '1')

	UPDATE VAITRO SET TENVAITRO =, TRANGTHAI = WHERE (MAVAITRO = '1')

	INSERT INTO VAITRO (MAVAITRO, TENVAITRO, TRANGTHAI) VALUES (,,)

SELECT * FROM   VAITRO

*/

-- Bảng TAIKHOAN
/*
	SELECT * FROM TAIKHOAN

	SELECT MAVAITRO, HOTEN, MATKHAU, NGAYSINH, GIOITINH, EMAIL, SDT, DIACHI, ANHDAIDIEN, NGAYTAO, TRANGTHAI FROM   TAIKHOAN WHERE (MANV = '1')

	DELETE FROM TAIKHOAN WHERE (MANV = '1')

	UPDATE TAIKHOAN SET MAVAITRO =, HOTEN =, MATKHAU =, NGAYSINH =, GIOITINH =, EMAIL =, SDT =, DIACHI =, ANHDAIDIEN =, NGAYTAO =, TRANGTHAI = WHERE (MANV = '1')

	INSERT INTO TAIKHOAN (MANV, MAVAITRO, HOTEN, MATKHAU, NGAYSINH, GIOITINH, EMAIL, SDT, DIACHI, ANHDAIDIEN, NGAYTAO, TRANGTHAI)
	VALUES (,,,,,,,,,,,)
*/
	
-- Bảng LOAIKHACHHANG
/*
	DELETE FROM LOAIKHACHHANG WHERE MALOAIKH = ?

	UPDATE LOAIKHACHHANG SET TENLOAIKH =?, TRANGTHAI =? WHERE MALOAIKH = ?

	INSERT INTO LOAIKHACHHANG (TENLOAIKH) VALUES (?)

	SELECT  * FROM   LOAIKHACHHANG
*/
	SELECT * FROM KHACHHANG
	UPDATE KHACHHANG set MALOAIKH = 2 WHERE TICHDIEM > 1000 
-- Bảng KHACHHANG
/*
	INSERT INTO KHACHHANG (MAKH, MALOAIKH, HOTEN,NGAYSINH, GIOITINH, EMAIL, SDT, DIACHI, NGAYTAO) VALUES (?,?,?,?,?,?,?,?,?)

	UPDATE KHACHHANG SET MALOAIKH =?, HOTEN =?, NGAYSINH =?, GIOITINH =?, EMAIL =?, SDT =?, DIACHI =?, NGAYTAO =?, TRANGTHAI =? WHERE MAKH=?

	DELETE FROM KHACHHANG WHERE MAKH = ?

	SELECT * FROM KHACHHANG

	SELECT * FROM KHACHHANG WHERE MAKH = ?

	SELECT MALOAIKH, HOTEN, NGAYSINH, GIOITINH, EMAIL, SDT, DIACHI, NGAYTAO, TRANGTHAI FROM   KHACHHANG WHERE (MAKH = '?')

	SELECT * FROM   KHACHHANG WHERE MALOAIKH = 1  and MAKH like 'null' or HOTEN like ?
*/

-- Bảng DONVITINH
/*
	UPDATE DONVITINH SET TENDVT =, TRANGTHAI = WHERE MADVT = ?

	INSERT INTO DONVITINH (TENDVT) VALUES ()

	SELECT TENDVT, TRANGTHAI FROM   DONVITINH WHERE (MADVT = ?)

	SELECT * FROM   DONVITINH
*/

-- Bảng MAUSAC
/*
	UPDATE MAUSAC SET TENMAU =, TRANGTHAI = WHERE MAMAU = ?

	INSERT INTO MAUSAC (TENMAU) VALUES ()

	SELECT TENMAU, TRANGTHAI FROM   MAUSAC WHERE (MAMAU = ?)

	SELECT * FROM   MAUSAC
*/
	
-- Bảng DANHMUC
/*
	UPDATE DANHMUC SET TENDANHMUC =?,NGAYTHEM=? TRANGTHAI =? WHERE MADM = ?

	INSERT INTO DANHMUC (TENDANHMUC,NGAYTHEM) VALUES (?,?)

	DELETE FROM DANHMUC WHERE MADM=?

	SELECT * FROM DANHMUC WHERE MADM=?

	SELECT * FROM DANHMUC
*/

-- Bảng SIZE
/*
	UPDATE SIZE SET TENSIZE =, TRANGTHAI = WHERE MASIZE = ?

	INSERT INTO SIZE (TENSIZE) VALUES ()

	SELECT TENSIZE, TRANGTHAI FROM   SIZE WHERE (MASIZE = ?)

	SELECT * FROM   SIZE
*/

-- Bảng CHATLIEU
/*
	UPDATE CHATLIEU SET TENCHATLIEU =, TRANGTHAI = WHERE MACHATLIEU = ?

	INSERT INTO SIZE (TENCHATLIEU) VALUES ()

	SELECT TENCHATLIEU, TRANGTHAI FROM   CHATLIEU WHERE (MACHATLIEU = ?)

	SELECT * FROM CHATLIEU
*/

-- Bảng SANPHAM
/*
	DELETE FROM SANPHAM WHERE MASP = ?

	UPDATE SANPHAM SET MADM =?, MAVACH =?, ANHSANPHAM =?, GIANHAP =?, GIABAN =?, SOLUONG =?, NGAYNHAP =?, APDUNGKM =?, MADVT =?, MAMAU =?, MASIZE =?, MACHATLIEU =?, TRANGTHAI =? WHERE MASP = ?

	INSERT INTO SANPHAM ( MASP, MADM, MAVACH, ANHSANPHAM, GIANHAP, GIABAN, SOLUONG, NGAYNHAP, APDUNGKM, MADVT, MAMAU, MASIZE, MACHATLIEU) VALUES (,,,,,,,,,,,,)

	SELECT MADM, MAVACH, ANHSANPHAM, GIANHAP, GIABAN, SOLUONG, NGAYNHAP, APDUNGKM, MADVT, MAMAU, MASIZE, MACHATLIEU, TRANGTHAI FROM   SANPHAM WHERE (MASP = ?)

	SELECT * FROM   SANPHAM
	
	SELECT * FROM   SANPHAM WHERE MADM =  100 and MASP like '%null%' or TENSP like '%%'	
*/
	
-- Bảng KHUYENMAI
/*
	DELETE FROM KHUYENMAI WHERE MAKM = ?

	UPDATE KHUYENMAI SET MASP =, TENKM =, HINHTHUCAD =, GIAMTOIDA =, NGAYBATDAU =, NGAYKETTHUC =, GIATRI =, TRANGTHAI = WHERE MAKM = ?

	INSERT INTO KHUYENMAI (MAKM, MASP, TENKM, HINHTHUCAD, GIAMTOIDA, NGAYBATDAU, NGAYKETTHUC, GIATRI) VALUES (,,,,,,,)

	SELECT MAKM, MASP, TENKM, HINHTHUCAD, GIAMTOIDA, NGAYBATDAU, NGAYKETTHUC, GIATRI TRANGTHAI FROM   KHUYENMAI WHERE (MAKM = ?)

	SELECT KHUYENMAI.* FROM   KHUYENMAI
*/

-- Bảng HOADON
/*
	DELETE FROM HOADON WHERE MAHOADON

	UPDATE HOADON SET MANV =, MAKH =, NGAYMUA =, GIAMGIA =, NGAYGIAOHANG =, TIENSHIP =, THANHTIEN =, TRANGTHAI = WHERE MAHOADON = ?

	INSERT INTO HOADON (MANV, MAKH, NGAYMUA, GIAMGIA, NGAYGIAOHANG, TIENSHIP, THANHTIEN, TRANGTHAI, MAHOADON) VALUES (,,,,,,,,)

	SELECT MANV, MAKH, NGAYMUA, GIAMGIA, NGAYGIAOHANG, TIENSHIP, THANHTIEN, TRANGTHAI FROM   HOADON WHERE (MAHOADON = ?)

	SELECT * FROM   HOADON WHERE MAHOADON = 10001

INSERT INTO HOADON
                  (MANV, MAKH, MATT, NGAYMUA, GIAMGIA, NGAYGIAOHANG, TIENSHIP, THANHTIEN)
VALUES (,,,,,,,)
*/

-- Bảng CTHOADON
/*
	DELETE FROM CT_HOADON WHERE (MAHD = 1)

	UPDATE CT_HOADON SET  SOLUONG = ?, GHICHU = ?, TRANGTHAI = ? WHERE MAHD = ? and MASP = ?

	INSERT INTO CT_HOADON (MASP, SOLUONG, GHICHU, MAHD) VALUES (,,,)

	SELECT MASP, SOLUONG, GHICHU, TRANGTHAI FROM   CT_HOADON WHERE (MAHD = 1)

	SELECT CT_HOADON.* FROM   CT_HOADON
*/
SELECT CT_HOADON.* FROM   CT_HOADON WHERE (MAHD = 10001)
--Giao Hàng
INSERT INTO GIAOHANG (MAHOADON, TENKHACHHANG, SDT, DIACHI, NGAYGIAOHANG, TIENSHIPHANG, GHICHU, MATT) VALUES (?,?,?,?,?,?,?,?)
UPDATE GIAOHANG SET TENKHACHHANG = ?, SDT = ?, DIACHI = ?, NGAYGIAOHANG = ?, TIENSHIPHANG = ?, GHICHU = ?, MATT = ? WHERE  (MAHOADON = ?)
DELETE FROM GIAOHANG WHERE  (MAGIAOHANG = ?)
SELECT * FROM GIAOHANG WHERE  (MATT = 2) AND (MAHOADON like '%14-4%'  or TENKHACHHANG like N'%14-4%' or SDT like '%14-4%' or DIACHI like N'%14-4%')
SELECT * FROM GIAOHANG 
SELECT * FROM   HOADON
select * from TT_HOADON
select * from KHACHHANG
select * from LOAIKHACHHANG

SELECT COUNT(MAGIAOHANG) FROM GIAOHANG WHERE MATT = 6 or MATT = 5

SELECT MAX(MAVACH) FROM SANPHAM
SELECT * FROM SANPHAM